[env:m5stack-core2]
platform = espressif32
board = m5stack-core2
framework = arduino

; WiFi + WebServer を積むと既定のパーティションでは容量が足りないため
; アプリ領域の大きい huge_app を使う(そのぶん OTA は使えなくなる)
board_build.partitions = huge_app.csv

lib_deps =
    m5stack/M5Unified

upload_port = /dev/cu.usbserial-5B1F0083251
upload_speed = 460800
monitor_port = /dev/cu.usbserial-5B1F0083251
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_flags =
    -D BUILD_UNIX_TIME=$UNIX_TIME
    -D CORE_DEBUG_LEVEL=0
